### PR TITLE
Fix typed property access before initialization

### PR DESCRIPTION
**Pull request by TheNewHEROBRINEX**

### CODE REVIEW

**Comment by TheNewHEROBRINEX** [comment]
By the way, there is a missing call to `GameRules::init()` that I cannot add because I don't know the gamerules defaults

**Comment by VixikHD** [comment]
There is resource with those

**Comment by TheNewHEROBRINEX** [comment]
Sorry the PR was closed because I renamed the branch. I'm going to open another one.

**Comment by TheNewHEROBRINEX** [comment]
> There is resource with those

Can you provide me with any link?

**Comment by VixikHD** [comment]
https://github.com/CzechPMDevs/MultiWorld/blob/master/resources/data/gamerules.yml

**Pull request closed without merging**
